version: '3.8'

services:
  elasticsearch:
    image: elasticsearch:7.17.13
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  flask:
    build:
      context: ./project/flask-app
      dockerfile: Dockerfile-flask

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "80:80"

volumes:
  es_data:
    driver: local