version: '3.8'
services:
 elasticsearch:
   image: docker.elastic.co/elasticsearch/elasticsearch:7.17.13
   container_name: elasticsearch
   healthcheck:
     test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health"]
     interval: 30s
     timeout: 10s
     retries: 5
   ports:
     - "9200:9200"
   environment:
     - discovery.type=single-node
     - "ES_JAVA_OPTS=-Xms512m -Xmx512m" 
     - xpack.security.enabled=false
   networks:
     - app-network

 flask-app:
   build:
     context: ./project/flask-app
     dockerfile: Dockerfile.light
   container_name: flask-app
   depends_on:
     elasticsearch:
       condition: service_healthy
   ports:
     - "5000:5000"
   environment:
     - FLASK_APP=app.py
     - FLASK_ENV=development
   networks:
     - app-network

 nginx:
   image: nginx:latest
   container_name: nginx
   ports:
     - "80:80"
   volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf:ro
     - ./nginx/static:/usr/share/nginx/html/static
   depends_on:
     - flask-app
   networks:
     - app-network

networks:
 app-network:
   driver: bridge