# Use the Nginx base image
FROM nginx:alpine

# Copy the Nginx configuration file
COPY nginx.conf /etc/nginx/nginx.conf

# Copy the React build files to Nginx
COPY ./project/flask-app/static /usr/share/nginx/html

# Expose ports 80 and 443
EXPOSE 80 443
