version: '3.8'

services:
  elasticsearch:
    build:
      context: .
      dockerfile: Dockerfile-elasticsearch
    container_name: elasticsearch-server
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Dlog4j2.formatMsgNoLookups=true
      - LOG_LEVEL=warn

  flask:
    build:
      context: ./project/flask-app
      dockerfile: Dockerfile-flask
    container_name: flask-server
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch
    environment:
      - FLASK_ENV=development

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    container_name: nginx-server
    ports:
      - "80:80"
    depends_on:
      - flask
