version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: lavagna
      MYSQL_USER: lavagna_user
      MYSQL_PASSWORD: lavagna_pass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-prootpass"]
      interval: 10s
      timeout: 5s
      retries: 3

  app:
    build: .
    environment:
      SPRING_PROFILES_ACTIVE: production
      DATASOURCE_DIALECT: MYSQL
      DATASOURCE_URL: jdbc:mysql://db:3306/lavagna?autoReconnect=true&useSSL=false
      DATASOURCE_USERNAME: lavagna_user
      DATASOURCE_PASSWORD: lavagna_pass
    depends_on:
      - db
    ports:
      - "8080:8080"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "8081:8081"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docs:/usr/share/nginx/html/docs
    depends_on:
      - app

networks:
  frontend-net:
  backend-net:
    internal: true

volumes:
  mysql_data:
