version: '3.8'

services:
  db:
    image: mysql:5.7
    networks:
      - backend-net
    environment:
      MYSQL_DATABASE: lavagna
      MYSQL_USER: lavagna_user
      MYSQL_PASSWORD: lavagna_pass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - mysql_data:/var/lib/mysql
    command: --character-set-server=utf8 --collation-server=utf8_bin
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-prootpass" ]
      interval: 10s
      timeout: 5s
      retries: 3

  app:
    build: .
    networks:
      - frontend-net
      - backend-net
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DATASOURCE_DIALECT=MYSQL
      - DATASOURCE_URL=jdbc:mysql://db:3306/lavagna?autoReconnect=true&useSSL=false
      - DATASOURCE_USERNAME=lavagna_user
      - DATASOURCE_PASSWORD=lavagna_pass

  nginx:
    image: nginx:alpine
    networks:
      - frontend-net
    ports:
      - "80:80"
      - "8081:8081"
    volumes:
      - ./src/main/webapp:/usr/share/nginx/html/static:ro
      - ./target/lavagna/help:/usr/share/nginx/html/docs:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

networks:
  frontend-net:
  backend-net:
    internal: true

volumes:
  mysql_data: