version: '3'
services:
  elasticsearch:
    image: elasticsearch:7.17.13
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    networks:
      - app-network

  flask-app:
    build: ./flask-app
    volumes:
      - ./flask-app/static:/app/static
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/static:/usr/share/nginx/html/static
    depends_on:
      - flask-app
    networks:
      - app-network

networks:
  app-network:
